bkhpanigha/hh-suttas

index.js

makes sure it stays the theme that's toggled on refresh

fix theme storage

---

.github/workflows/update_suttas_list.yml
available_suttas.json
available_suttas.py
index.js

when one adds a new json file to the suttas folder (or updates an existing one's title) by committing and pushing it. A github action will run in the background that will read all the json files and get their titles to put in available_suttas.json

#1 update front page formatting + github action to update sutta list

---

.github/workflows/update_suttas_list.yml
available_suttas.json
available_suttas.py
index.html
index.js

basic search while maintaining citation functionality. Might not be needed right now but here as a proof of concept.

#2 Search initial implementation

---

.github/workflows/update_suttas_list.yml
available_suttas.json
available_suttas.py
index.html
index.js

supports highlighting for individual section and range of ids. Needs further work with making the highlighting aesthetics better. 
domain.com/?q=mn1#mn1:23.1
domain.com/?q=mn1#mn1:23.1-mn1:194.6

#3 Highlighting mvp

---

index.css
index.js
utils.js

Closes #33 
fix bug with comments being escaped. Logic should also be cleaner now.
also fixed issue with copy link button being shown on comment text selection

Bug comments display

---

index.css

Noticed this strange bug on ipad. Trying to see if setting it to px fixes it

Fix nested css

---

index.html
index.js

fixed foreword text in dark mode and doubling of suttas list

fix dark mode and double sutta list

---

available_suttas.json

Removed spaces in suttas IDs in available_suttas.json so as to facilitate search processing without adding more code

Removed spaces in suttas IDs

---

index.js

As per @Reptilioo 's point. This fixes the search results being appended to the bottom

Bug search foreword

---

suttas/translation_en/mn/mn53_translation-en-anigha.json

Correcting typos in MN53 translation

Correcting typos in MN53 translation

---

index.css
index.js

Shows a message when there are no results

---

index.js

Puts back search on headings that got removed with recent changes

Allow search on headings

---

index.css
index.js
js/utils.js

First version of new comments format

Comments relocation

---

.github/workflows/buildTestDeploy.yml
index.css
index.html
index.js

Whats new section

---

.github/workflows/buildTestDeploy.yml

Fix date added

---

suttas/translation_en/mn/mn43_translation-en-anigha.json

correcting the translation of
> Yaṁ hāvuso, vedeti taṁ sañjānāti, yaṁ sañjānāti taṁ vijānāti.

mn 43 typo

---

index.js

Fix pali not showing & document title issue

---

bookmarks.js
index.css

An attempt to slightly improve Bookmarks' Layout and readability as asked in #140

Bookmarks' Layout Improvement

---

index.css
index.js

fix broken formatting and pali toggle

---

index.html

We begin to have a lot of buttons, just want to make it easier for people to know what they are clicking

Add titles to buttons

---

sw.js

Fix an issue with the "Use Offline" button where the caching will fail because it can't find "available_suttas.json" anymore.

Fix "Use Offline" issue

---

comments.js
index.js
js/utils/getDocumentAreas.js
js/utils/loadContent/activateEventListeners.js

For reference, issue was added in #192 and #180.
Also fix an issue on "comment.html" where "comment.js" can't find "available_suttas.json" anymore.
closes #199

Fix suttas not showing on localhost

---

python/scripts/epub_book_generator.py

Fix all table of contents links pointing to page 1

---

.github/workflows/buildTestDeploy.yml

I have finally found out that I could test github actions on my fork, so this time this will work.
We check if there is change in "/suttas" in the last commit.
- if there is: we setup python and its dependencies, then we run the 4 pythons scripts that are processing "/suttas" (of which the epub generator), and then we push any changes.
- if there isn't: we push any changes.

Fix EPUB generation issue

---

js/utils/navigation/highlightSegments.js
js/utils/navigation/scrollToHash.js

Fix passage link with compound verse issue

---

index.css
js/utils/loadContent/buildSutta.js

Add sutta navigation buttons (next/previous)

---

advanced-search.html
js/utils/LoadingBarManager.js
js/utils/contentSections/SuttaSearch.js
js/utils/contentSections/searchSuttasWithStop.js
js/utils/eventListeners/initializeSearchEvents.js

- Added 3 chars minimum in seach bar for search button to be enabled.
- Removed the limitations to 10 results maximum (and its reference in the html).
- Improved the results display so if a result is ready to show it is instantly displayed instead of waiting for the whole sutta to be processed.
- Improved the loading bar behavior.

Advanced search modifications

---

index.html
js/utils/navigation/redirectSuttaUrl.js

I think I should have most possibilities covered for the existing books and therefore "old" links, if not all.
I also wonder if there could be a better way to do it, but at least that should do the job for now.

Redirect old link format to new

---

advanced-search.css
advanced-search.html
advanced-search.js
bookmarks.html
bookmarks.js
comments.html
comments.js
glossary.html
glossary.js
index.css
index.html
index.js
js/utils/misc/toggleTheme.js
js/utils/navigation/preventFlashing.js
js/utils/navigation/redirectSuttaUrl.js

Fix dark mode flashing white then black when displaying/refreshing the page.
Contains modifications from #226

Fix dark mode flashing

---

advanced-search.css
advanced-search.js
js/utils/eventListeners/initializeSearchEvents.js

- Automatically hide "Search Options" panel when touching Enter, like it already does when clicking "Search" button.
- Reorganized code handling menu behaviors.

Improves advanced search menu on mobile

---

index.js
js/utils/loadContent/buildSutta.js

Prevents flashing (foreword showing and no content displayed quickly followed by sutta content loaded) when loading a sutta.
closes #189

Fix more flashing

---

index.css
index.html

Right now, when accessing a sutta offline all we get is a blank page.

Fix offline blank page

---

js/utils/navigation/YoutubePreview.js

- More responsive
- Cleaner animations
- Less likely to stay stuck displayed, on desktop
- Preload data so they are not fetched every display
- Prettier preview offline

Youtube Preview Improvements

---

index.css
js/utils/loadContent/buildSutta.js

- Add max width for navigation buttons
- Add gap between buttons
- Add right alignment of text for "Next" button
Old:
New:

Improve sutta navigation buttons

---

js/utils/contentSections/SuttaSearch.js

- Fix a bug where the searched term would not appear in a displayed passage in the search results, if the matching word is at the end of the sutta. 
e.g. when searching "influxes", in the last search result for SN 22.81.
- Fix a bug where the end of the sutta would not be displayed in the passage, even though the matching word is next to the end of the passage.
e.g when searching "immediate destruction", in the last search result for SN 22.81.
- Some cleaning up

Bug fix in search panel

---

index.css

- Remove card elevation on hover, it was sometimes causing an unwanted blurry effect.
- Make the separator above the description lighter.
- Make the borders around dark sutta cards darker.
- Keep the filter bar "hovered" while focused.
- Make sutta cards clickable on their edges.

Homepage redesign modifications

---

sw.js

The caching system for offline use doesn't overwrite existing files by default; instead, it ignores them, preventing new file versions from being cached.
This change resolves the issue by removing the file before caching it.
closes #267

Fix offline recaching

---

js/utils/eventListeners/activateTopButtonsTouchAnimation.js

Fix navbar not working on touchscreens

---

js/utils/contentSections/SuttaSearch.js

Fix search panel ellipses in comments

---

index.css
js/utils/contentSections/displaySuttas.js

I went with this style:
Let me know if we should rather go with a style more similar to the previous one like:

Eye-catching headings

---

js/utils/contentSections/SuttaSearch.js

Changes the calculation to know if we are near the end of the text, from a pourcentage based on the text length to just checking if we are below maxWords length.
closes #285

Fix search passages that are longer than they should

---

js/utils/eventListeners/initializeSearchEvents.js
search-panel.js

I forgot to commit the part hiding the header when clicking `Search Panel` button.

Fix better search button position
