index.js, readMe.md, sw.js
Closes #36 
- add License in readme
- Made message more relevant when user navigated to a sutta that doesn't exist
- updated cache name because my browser was still using the old sw.js (from a while back). It seems changing the cache name does the trick (and apparently should be updated whenever the sw.js is updated. Need to confirm this 100%)
- Removed space from citations from main page links
- clean up acknowledgement text
=> Minor cleanups

.github/workflows/buildTestDeploy.yml
closes #49 
I'm still not exactly sure why there were conflicts in the merge operations (in theory new commits from `main` should just slot in on top of the last commit in `gh-pages`). Nonetheless, we now just take the current state of `main` as it force push it to `gh-pages`
=> checkout gh-pages from main and force push

.github/workflows/buildTestDeploy.yml
The commit from the catalogue manager isn't being pushed to gh-pages. So now we've added a fetch before
=> fetch before checking out gh-pages

index.js
- When doing a search the results were classified in the wrong Nikaya section (e.g. MN2 would be displayed after "Dīgha Nikāya" when searching for 'MN2') -> Removed displaying of the Nikaya `<h2>` when searching.
- Fixed an issue where the search wasn't done on titles, authors and headings fields too.
- Excluded search results that don't have anything to do with the search pattern (e.g. SN12.67 could appear when searching for 'MN1')
=> Fix some issues with search function

js/utils.js
Added conditions to move through siblings without catching errors and displaying a "page not found" text when the link hash contains references to the sutta title segment or to the first line of the sutta segment.
Edit: Might need a proper refactoring or rethinking of the suttas .html files later for a cleaner code
=> Fix Issue #82

index.css
`<h5>` pali titles were still visible after hiding pali  
e.g. DN2
=> Hide <h5> pali titles when toggling off pali

index.js
document.title and #suttanav were undefined on some suttas because the title wasn't fetch at the right line.
Now: the title is directly extracted from the Promise retrieving the sutta's content.
=> Fix Issue #87

index.js
closes #78 
Bypass Fusejs limitation not allowing to search for fragments of keywords accross multiple fields [id, title, pali_title, heading, author] (e.g. "sn mind" for SN35.246) by combining every fields in a single one
=> Allows search on multiple fields

js/utils.js, sutta_catalog_manager.py, sw.js
closes #108 
The issue came from the fact that when the root dir was added to the directories to cache, it cached every subdirectories in it, so every dirs and files from the project were cached resulting in a large number of files being pulled at once and in fetches errors because the browser (??) couldn't keep up.
**Solution:** 
- Cache only files when the current processed dir is "./", otherwise cache all files and subdirs.
**Additional:** 
- Modified the caching logic in sw.js so the files are cached in batch in order to not face the same issue arising because too many files were fetched at once.
=> Fix files caching issue

js/utils.js
Issue #113 was about two issues:
1) For collections of suttas like AN.1.51-60, the sutta's IDs contained in the segments of the html aren't the same as the sutta id we are going to find in the url for the ```?q=``` parameter.
So when copying a link, the id extracted wasn't correct: instead of ```?q=an1.51-60```, we got ```?q=an1.51``` or ```?q=an1.52``` etc, depending on the segment copied.
2) Function ```generateLink()``` receive as a parameter the range of verses to link to, separated by a dash (e.g., ```mn11:4.1-mn11:4.5```), which was problematic when the first part of the verse contained a dash itself.
**Solution:**
Fetch the sutta's id in the current url when displaying the page and keep it in memory.
Fetch this id in generateLink() instead of reading it from the values in the range …
=> Fix Issue #113

index.js
Remove side-by-side when toggling pali off to fix issue: 
when turning pali off on a page where side-by-side mode is activated -> titles on next visited pages were still showing side-by-side 
closes #145
=> Remove side-by-side when toggling pali off

index.css, index.js
- Fix box-shadow not showing on highlights when displaying pali: now it will show on the english part when pali is displayed.
- Add box-shadow on highlighted comments: had to add ```<span>``` elements around comments for it to work.
- Increase obviousness of highlights when in dark mode (box-shadow isn't used in dark mode) by increasing font-size.
closes #162
=> Fix issues with highlighting

index.css
Correct highlighting bug where the box-shadow around the highlighted passage doesn't show on a blockquote like the one at the end of SN 35.94
=> Correct highlighting bug

js/utils/navigation/scrollToHash.js
Fix issue that gives "not a valid citation" error when following a link to a portion of text e.g. https://suttas.hillsidehermitage.org/?q=mn1#mn1:2.2-mn1:2.3
Also fixes links to comment and links at the end of comment to paragraph linking to comment.
closes #196.
@bkhpanigha
=> Fix issue with link to portion of text giving an error

.github/workflows/buildTestDeploy.yml
Right now the EPUB is generated everytime buildTestDeploy.yml runs, though nothing changes in the book, the compression process itself actually gives a different file everytime, just a few bytes of difference, but enough to push this "new" file on the main branch **everytime**.
This slight modification of buildTestDeploy.yml aims at checking if there are actual changes in the translations or comments by checking if there are changes in `python/generated/suttas-database-data.json` and only then generate a new EPUB.
=> Fix issue with epub generation

bookmarks.html, comments.html, glossary.html, header.html, index.html, js/utils/contentSections/loadHeader.js
One thing to note for those using `live-server` as their local http server, it seems to only show the first 3 icons because it injects something for the auto-reload I'm told. So a way around it would be to use a python http server with the following command:
```
python -m http.server 8080
```
=> abstract header bar and icons

js/utils/misc/generateLink.js, js/utils/navigation/highlightSegments.js, js/utils/navigation/scrollToHash.js, js/utils/navigation/showCopyButton.js
Modify verse range separator from "-" to "_" in the url hash, so as to make processing the compound ids using "-" easier.
Handles ids like:
- an1.1:1.1
- an1.10:1.1
- an1.1-20:1.1
- mn28:29-30.1
- thag2.36:2.4
- snp4.2:4.1
=> Fix passage link with compound verse issue

js/utils/contentSections/SuttaSearch.js, js/utils/contentSections/searchSuttasWithStop.js
Right now the max words a passage can have on mobile isn't changed (100 pl/150 en).
Make it work as intended (50 pl/75 en).
Also optimize the logic for getting maxWords, from calling it for every passage, to only once per search.
=> Fix Advanced-Search max words displayed on mobile

.github/workflows/scheduledTasks.yml
Simplify the code to only add ```python/generated/available_videos.json``` if it was changed by ```python/scripts/fetch_videos_data.py```.
For an unknown reason, the first time it launches it will replace the whole file's content, but subsequent launches will only add the missing new videos.
=> Fix new github action failing

js/utils/contentSections/addResultToDOM.js, js/utils/contentSections/searchSuttasWithStop.js
The script lacked a chapter search function ("MN 1", "DN 10", ...).
Search results will be displayed no matter if the search term uses space or not ("MN1" and "MN 1" will match). Also applies with "Exact Match" on.
Also, fixed a bug that prevented the display of results that only matched with the title/heading and not the content in itself. It would work for the first match but not the subsequent ones.
=> Adv-search: Add search on chapters

advanced-search.css, advanced-search.html, js/utils/contentSections/addResultToDOM.js, js/utils/contentSections/searchSuttasWithStop.js
- Will display comments only even if 'en' and 'pali' are disabled, or if 'en' is disabled and 'pali' is enabled.
- Right now the results are mixed between english and pali. Aims to always display translation first, then comment, then pali for a given sutta.
- ~~When 'en' and 'pali' are enabled, added ```[EN]``` and ```[PLI]``` next to title to differentiate them at first glance.~~ [Similar modification added in next PR]
- ~~Also changed ```Title - Comments``` to ```Title [Comments]``` for comment related results.~~ [Similar modification added in next PR]
=> Adv. search improvements

js/utils/eventListeners/activateCacheButton.js, sw.js
- Revert the previous PR: Instead of deleting each files before caching their new version, delete all previous cache versions and create a new one -> prevents the need to modify the caching version everytime a file is manually added to `sw.js`.
- Remove the current cache if there were errors during the caching -> prevents issues like #267 one.
- Don't start the caching process if the user is not connected to internet.
- Warn the user that the caching error may come from internet connection issues.
=> Offline caching stability fix

index.css, js/utils/eventListeners/activateCacheButton.js, js/utils/eventListeners/activateMessageListener.js, js/utils/eventListeners/activateSideBySideEventListenerKeyUp.js, js/utils/eventListeners/activateTopButtonsTouchAnimation.js, js/utils/loadContent/activateEventListeners.js
- Modify Side-By-Side Pali display activation conditions: a change was needed since `#search-bar` became `#filter-bar`, otherwise it is possible that the side-by-side mode is activated by typing "s" in the filter bar.
- Add a click animation on the top buttons on mobile, the usual hover animation stays as long as the user is pressing the button. (most useful for the `Theme` button, since the others send the user to another page, refreshing the buttons in the process)
- Make sure that `navigator.serviceworker` is set and available before using it anywhere. So we don't get a js error and all the other js code not working because of it.
closes #270
=> Fix some issues

js/utils/loadContent/addNavbar.js, js/utils/navigation/scrollToHash.js
- Don't show navbar when the scroll is done because of scrollToHash(): the navbar will not be shown when the user click to the ```←``` to come back from where he left off.
- When using a link to a comment, or a link back from a comment to a passage -> additionnaly scroll down ~4-5 lines so the comment, or the passage where the user left off, isn't directly at the very top of the page.
closes #278
=> Fix hidden line when coming back from comment

js/utils/contentSections/displaySuttas.js, js/utils/contentSections/loadWhatsNewArea.js
Add space between letters and numbers in sutta IDs displayed on the home page (e.g.: ```MN44``` becomes ```MN 44```).
Feel free to dismiss/close if not appropriate.
=> Add space in sutta IDs on homepage

js/utils/navigation/scrollToHash.js
- Only scroll up to show previous line if the linked passage isn't at the bottom of the page, which would result in hiding it or part of it.
- Also, fixed an issue where the auto scroll to the linked comment was made before youtube links were displayed correctly, resulting in the scroll position being shifted and the linked comment hidden because of it, in some cases.
closes #282
=> Fix auto scroll issue

index.css, js/utils/eventListeners/activateWindowEventListeners.js
In the CSS the mobile header is configured to be rightly displayed from 768px and below so went from mobile header being displayed from 1000px and below to 768px and below (width of screens/windows).
closes #287
=> Fix mobile header not displaying properly on some screensizes

index.css, js/utils/eventListeners/initializeSearchEvents.js, js/utils/loadContent/activateEventListeners.js, search-panel.js
On mobile, whenever the mobile header gets hidden on the search panel page, the `Search Panel` button will follow and moves at the top of the screen, in place of the header.
Also, if the search panel is open and the mobile header is shown, the `Search Panel` button is displayed on top of the search panel, to resolve this in a simple manner I made it so the mobile header gets hidden whenever the user clicks on the `Search Panel` button.
closes #289
=> Moves the Search Panel button on mobile when header is hidden
